# Generated by Django 6.0.3 on 2026-03-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-timestamp']},
        ),
    ]
